# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM python:3.10-alpine

# set working directory
WORKDIR /app

# copy local project code to the container
COPY . /app

# install prerequisites if needed
# Install requirements only if files exist
RUN if [ -f requirements.txt ]; then pip install --no-cache-dir -r requirements.txt; fi \
    && if [ -f MCP/requirements.txt ]; then pip install --no-cache-dir -r MCP/requirements.txt; fi

# expose default MCP port (optional)
EXPOSE 13377

# Command to start MCP server
CMD [ "python", "-u", "MCP/unreal_mcp_bridge.py" ]
